In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
a.ndim

1

In [3]:
a.shape

(4,)

In [4]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a.ndim

2

In [5]:
a.shape

(2, 4)

In [6]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
a[1][2]

7

In [8]:
a=np.array([[[1,2,3,4],[5,6,7,8]]])
print(a)

[[[1 2 3 4]
  [5 6 7 8]]]


In [9]:
print(a.shape)

(1, 2, 4)


In [10]:
a.ndim

3

In [11]:
a[0][1][2]

7

In [13]:
a=np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [15]:
a=np.arange(1,61).reshape(10,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]
 [55 56 57 58 59 60]]


In [16]:
a[1][3]

10

In [17]:
a=np.arange(1,61).reshape(5,2,6)
print(a)

[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]]

 [[13 14 15 16 17 18]
  [19 20 21 22 23 24]]

 [[25 26 27 28 29 30]
  [31 32 33 34 35 36]]

 [[37 38 39 40 41 42]
  [43 44 45 46 47 48]]

 [[49 50 51 52 53 54]
  [55 56 57 58 59 60]]]


In [18]:
a[1][0][3]

16

In [1]:
import numpy as np

In [5]:
a=np.linspace(11,20,5)
print(a)

[11.   13.25 15.5  17.75 20.  ]


In [8]:
a=np.zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
a=np.ones((3,3),dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
a=np.diag([1,2,3,4])
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [16]:
## random vandit

In [17]:
a=np.random.randint(10,20)
print(a)

17


In [18]:
a=np.random.rand(3,3)
print(a)

[[0.35356353 0.1656598  0.36992087]
 [0.99206241 0.92375383 0.93461682]
 [0.24721001 0.279733   0.77951127]]


In [19]:
a=np.random.randn(3,3)
print(a)

[[ 0.85146983 -0.34571479 -0.64719597]
 [-1.63421768 -0.46505874 -0.30787174]
 [-0.68132984 -0.48043806  0.12803292]]


In [20]:
a=np.random.random((3,3))
print(a)

[[0.66260325 0.49715813 0.64823083]
 [0.29661984 0.79294384 0.57745952]
 [0.32381808 0.66722451 0.33794667]]


In [21]:
a=np.eye(2,2)
print(a)

[[1. 0.]
 [0. 1.]]


In [22]:
a=np.eye(3,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
a=np.full((3,3),9,dtype=int)
print(a)

[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [30]:
a=np.array([[1,2,5,6],[11,12,13,14]])
print(a)
b=a.ravel()
print(b)


[[ 1  2  5  6]
 [11 12 13 14]]
[ 1  2  5  6 11 12 13 14]


In [33]:
a=np.array([[1,2,5,6],[11,12,13,14]])
print(a)
b=a.T
print(b)
print(b.shape)


[[ 1  2  5  6]
 [11 12 13 14]]
[[ 1 11]
 [ 2 12]
 [ 5 13]
 [ 6 14]]
(4, 2)


In [38]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.array([[11,12,13,14],[15,16,17,18]])
c=np.concatenate([a,b])
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [11 12 13 14]
 [15 16 17 18]]


In [39]:
a=np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [40]:
b=np.arange(31,41).reshape(2,5)
print(b)

[[31 32 33 34 35]
 [36 37 38 39 40]]


In [42]:
c=np.vstack((a,b))
print(c)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [31 32 33 34 35]
 [36 37 38 39 40]]


In [43]:
a=np.arange(1,11).reshape(2,5)
print(a)
b=np.arange(31,41).reshape(2,5)
print(b)
c=np.hstack((a,b))
print(c)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[31 32 33 34 35]
 [36 37 38 39 40]]
[[ 1  2  3  4  5 31 32 33 34 35]
 [ 6  7  8  9 10 36 37 38 39 40]]


In [44]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.sum(a,axis=1)
print(b)


[10 26]


In [45]:
a=np.array([[1,2,3,4],[5,6,7,8]])
b=np.sum(a,axis=0)
print(b)


[ 6  8 10 12]
